ALTER TABLE incident ADD COLUMN restricting_access tinyint(1) default 0;

INSERT INTO `form` (`id`, `form_title`, `form_description`, `form_active`) VALUES
(2, 'Acceso y Resoluciones', 'Categorias de acceso y resoluciones', 1);

INSERT INTO `form_field` (`id`, `form_id`, `field_name`, `field_type`, `field_required`, `field_options`, `field_position`, `field_default`, `field_maxlength`, `field_width`, `field_height`, `field_isdate`, `field_ispublic_visible`, `field_ispublic_submit`) VALUES
(1, 2, 'Posible restricción al acceso humanitario', 6, 0, 'NULL', 1, 'cat_3¬Restricciones o interferencia con el paso de agencias, personal o bienes en el país (Según <a href="http://www.colombiassh.org/gtmi/wiki/index.php/Restricci%C3%B3n_al_acceso_humanitario" target="_blank">categoría 3 ?</a>)\r\n|cat_4¬Operaciones militares y hostilidades continuas impidiendo a las operaciones humanitarias (Según <a href="http://www.colombiassh.org/gtmi/wiki/index.php/Restricci%C3%B3n_al_acceso_humanitario" target="_blank">categoría 4 ?</a>)\r\n|cat_5¬Amenazas y violaciones encontra el personal humanitario y sus instalaciones (Según <a href="http://www.colombiassh.org/gtmi/wiki/index.php/Restricci%C3%B3n_al_acceso_humanitario" target="_blank">categoría 5 ?</a>)\r\n|cat_7¬Presencia de minas (MAP) y ordenanza no explotada (MUSE) (Según <a href="http://www.colombiassh.org/gtmi/wiki/index.php/Restricci%C3%B3n_al_acceso_humanitario" target="_blank">categoria 7 ?</a>)\r\n|cat_9¬Restricciones sobre, o obstrucción de, acceso a servicios y asistencia por parte de las poblaciones (Según <a href="http://www.colombiassh.org/gtmi/wiki/index.php/Restricci%C3%B3n_al_acceso_humanitario" target="_blank">categoria 9 ?</a>)', 0, 0, 5, 0, 0, 0),
(2, 2, 'Resoluciones', 6, 0, 'NULL', 2, 'res_1612¬Evento asociado con resolución 1612 ( <a href="http://www.colombiassh.org/gtmi/wiki/index.php/Resoluci%C3%B3n_1612_del_Consejo_de_Seguridad" target="_blank">Menores de edad en conflicto armado ?</a> )\r\n|res_1820¬Evento asociado con resolución 1820 ( <a href="http://www.colombiassh.org/gtmi/wiki/index.php/Resoluci%C3%B3n_1820_del_Consejo_de_Seguridad" target="_blank">Violencia sexual en conflicto armado ?</a> )', 0, 0, 5, 0, 0, 0);

